hv_blog_homepage:
  path: /{page}
  defaults:
    _controller: HVBlogBundle:Main:index
    page: 1
  requirements:
    page: \d*

hv_blog_view:
  path: /view/{id}
  defaults:
    _controller: HVBlogBundle:Main:view
  requirements:
      id: \d+

hv_blog_add:
  path: /add
  defaults:
    _controller: HVBlogBundle:Main:add

hv_blog_edit:
  path: /edit/{id}
  defaults:
    _controller: HVBlogBundle:Main:edit
  requirements:
    id: \d+

hv_blog_delete:
  path: /delete/{id}
  defaults:
    _controller: HVBlogBundle:Main:delete
  requirements:
    id: \d+
